# Linear Regression 

In [2]:
# !pip install pandas_profiling

     ------------------------------------ 328.8/328.8 kB 377.4 kB/s eta 0:00:00
  Using cached htmlmin-0.1.12.tar.gz (19 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
  Using cached visions-0.7.5-py3-none-any.whl (102 kB)
     ------------------------------------ 663.5/663.5 kB 491.9 kB/s eta 0:00:00
     ---------------------------------------- 2.1/2.1 MB 810.9 kB/s eta 0:00:00
  Using cached tangled_up_in_unicode-0.2.0-py3-none-any.whl (4.7 MB)
     ------------------------------------ 296.5/296.5 kB 763.5 kB/s eta 0:00:00
  Created wheel for htmlmin: filename=htmlmin-0.1.12-py3-none-any.whl size=27096 sha256=0b69a7f7882ade79f1adc3b97ee74c4ec6ee75bd8acaff0bd890d4127d53f291
  Stored in directory: c:\users\win11\appdata\local\pip\cache\wheels\ab\a0\78\885e94cd7af32ff120febdad1870c5381c884d7f4b332d58dd
Successfully built htmlmin
  Attempting uninstall: typing-extensions
    Found existing installation: typing_extensions 4.1.1
 

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import pickle
from pandas_profiling import ProfileReport
import numpy as np

In [2]:
df=pd.read_csv(r"H:\dataset_csv\advertising (1)FSDS bootcamp2.0.csv")

In [3]:
df.head()

TV  Radio  Newspaper  Sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3   12.0
3  151.5   41.3       58.5   16.5
4  180.8   10.8       58.4   17.9

In [4]:
pf=ProfileReport(df)

In [5]:
pf.to_widgets()

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render widgets:   0%|          | 0/1 [00:00<?, ?it/s]

In [16]:
#  pf.to_file("lr_report.html")

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

In [4]:
df.describe()

TV       Radio   Newspaper       Sales
count  200.000000  200.000000  200.000000  200.000000
mean   147.042500   23.264000   30.554000   15.130500
std     85.854236   14.846809   21.778621    5.283892
min      0.700000    0.000000    0.300000    1.600000
25%     74.375000    9.975000   12.750000   11.000000
50%    149.750000   22.900000   25.750000   16.000000
75%    218.825000   36.525000   45.100000   19.050000
max    296.400000   49.600000  114.000000   27.000000

In [5]:
df.columns

Index(['TV', 'Radio', 'Newspaper', 'Sales'], dtype='object')

In [6]:
x=df[["TV"]]
y=df["Sales"]

In [7]:
from sklearn.linear_model import LinearRegression
linear=LinearRegression()

In [8]:
linear.fit(x,y)

LinearRegression()

In [9]:
linear.intercept_   # y=mx+c ...so here c is intercept

6.974821488229891

In [10]:
linear.coef_        # y=mx+c ...so here m is coef

array([0.05546477])

In [11]:
file='linear_reg.sav'
pickle.dump(linear,open(file,'wb'))

In [12]:
linear.predict([[45]])

C:\Users\win11\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([9.47073616])

In [13]:
linear.predict([[230]])

C:\Users\win11\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([19.7317187])

In [14]:
l=[45,78,230,56,78]

In [15]:
for i in l:
    print(linear.predict([[i]]))

[9.47073616]
[11.30107358]
[19.7317187]
[10.08084863]
[11.30107358]


C:\Users\win11\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\Users\win11\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\Users\win11\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\Users\win11\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\Users\win11\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


In [16]:
saved_load=pickle.load(open(file,'rb'))

In [17]:
saved_load.predict([[45]])

C:\Users\win11\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([9.47073616])

In [18]:
linear.score(x,y)

0.8121757029987414

## 2nd Part --> next day

In [19]:
df.head()

TV  Radio  Newspaper  Sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3   12.0
3  151.5   41.3       58.5   16.5
4  180.8   10.8       58.4   17.9

In [21]:
data_x=df[['TV', 'Radio', 'Newspaper']]
y=df["Sales"]

In [23]:
lr=LinearRegression()

In [24]:
lr.fit(data_x,y)

LinearRegression()

In [33]:
lr.intercept_

4.62512407880865

In [34]:
lr.coef_

array([0.05444578, 0.10700123, 0.00033566])

In [35]:
lr.score(data_x,y)

0.9025912899684558

In [37]:
# statics model--

import statsmodels.formula.api as snf

In [40]:
lm=snf.ols(formula='Sales~ TV',data=df).fit()
lm.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                  Sales   R-squared:                       0.812
Model:                            OLS   Adj. R-squared:                  0.811
Method:                 Least Squares   F-statistic:                     856.2
Date:                Mon, 30 Jan 2023   Prob (F-statistic):           7.93e-74
Time:                        21:27:26   Log-Likelihood:                -448.99
No. Observations:                 200   AIC:                             902.0
Df Residuals:                     198   BIC:                             908.6
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      6.9748      0.323     21.624      0.000       6.339       7.611
TV             0.0555      0.002     29.260      0.000       0.052       0.059
==============================================================================
Omnibus:                        0.013   Durbin-Watson:                   2.029
Prob(Omnibus):                  0.993   Jarque-Bera (JB):                0.043
Skew:                          -0.018   Prob(JB):                        0.979
Kurtosis:                       2.938   Cond. No.                         338.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [44]:
lm=snf.ols(formula='Sales~ Radio',data=df).fit()
lm.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                  Sales   R-squared:                       0.122
Model:                            OLS   Adj. R-squared:                  0.118
Method:                 Least Squares   F-statistic:                     27.57
Date:                Mon, 30 Jan 2023   Prob (F-statistic):           3.88e-07
Time:                        21:30:32   Log-Likelihood:                -603.18
No. Observations:                 200   AIC:                             1210.
Df Residuals:                     198   BIC:                             1217.
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     12.2357      0.653     18.724      0.000      10.947      13.524
Radio          0.1244      0.024      5.251      0.000       0.078       0.171
==============================================================================
Omnibus:                       11.077   Durbin-Watson:                   2.018
Prob(Omnibus):                  0.004   Jarque-Bera (JB):                9.124
Skew:                          -0.433   Prob(JB):                       0.0104
Kurtosis:                       2.414   Cond. No.                         51.4
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [41]:
lm=snf.ols(formula='Sales~ TV+Radio+Newspaper',data=df).fit()
lm.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                  Sales   R-squared:                       0.903
Model:                            OLS   Adj. R-squared:                  0.901
Method:                 Least Squares   F-statistic:                     605.4
Date:                Mon, 30 Jan 2023   Prob (F-statistic):           8.13e-99
Time:                        21:29:14   Log-Likelihood:                -383.34
No. Observations:                 200   AIC:                             774.7
Df Residuals:                     196   BIC:                             787.9
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      4.6251      0.308     15.041      0.000       4.019       5.232
TV             0.0544      0.001     39.592      0.000       0.052       0.057
Radio          0.1070      0.008     12.604      0.000       0.090       0.124
Newspaper      0.0003      0.006      0.058      0.954      -0.011       0.012
==============================================================================
Omnibus:                       16.081   Durbin-Watson:                   2.251
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               27.655
Skew:                          -0.431   Prob(JB):                     9.88e-07
Kurtosis:                       4.605   Cond. No.                         454.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [46]:
lm=snf.ols(formula='Sales~ TV+Radio',data=df).fit()
lm.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                  Sales   R-squared:                       0.903
Model:                            OLS   Adj. R-squared:                  0.902
Method:                 Least Squares   F-statistic:                     912.7
Date:                Mon, 30 Jan 2023   Prob (F-statistic):          2.39e-100
Time:                        21:39:34   Log-Likelihood:                -383.34
No. Observations:                 200   AIC:                             772.7
Df Residuals:                     197   BIC:                             782.6
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      4.6309      0.290     15.952      0.000       4.058       5.203
TV             0.0544      0.001     39.726      0.000       0.052       0.057
Radio          0.1072      0.008     13.522      0.000       0.092       0.123
==============================================================================
Omnibus:                       16.227   Durbin-Watson:                   2.252
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               27.973
Skew:                          -0.434   Prob(JB):                     8.43e-07
Kurtosis:                       4.613   Cond. No.                         425.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [49]:
lm=snf.ols(formula='Sales~ Radio+Newspaper',data=df).fit()
lm.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                  Sales   R-squared:                       0.124
Model:                            OLS   Adj. R-squared:                  0.115
Method:                 Least Squares   F-statistic:                     13.89
Date:                Mon, 30 Jan 2023   Prob (F-statistic):           2.28e-06
Time:                        21:40:56   Log-Likelihood:                -603.03
No. Observations:                 200   AIC:                             1212.
Df Residuals:                     197   BIC:                             1222.
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     12.0607      0.728     16.556      0.000      10.624      13.497
Radio          0.1195      0.025      4.708      0.000       0.069       0.170
Newspaper      0.0095      0.017      0.548      0.585      -0.025       0.044
==============================================================================
Omnibus:                       11.760   Durbin-Watson:                   2.013
Prob(Omnibus):                  0.003   Jarque-Bera (JB):                9.377
Skew:                          -0.434   Prob(JB):                      0.00920
Kurtosis:                       2.389   Cond. No.                         92.0
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""