In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import Ridge,Lasso,RidgeCV,ElasticNetCV,LinearRegression
from sklearn.model_selection import train_test_split
import statsmodels.api as sn
import matplotlib.pyplot as plt
import seaborn as sns

ModuleNotFoundError: No module named 'statsmodels'

In [2]:
df=pd.read_csv(r"H:\dataset_csv\Admission_Predict.csv")
df.head()

Serial No.  GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  \
0           1        337          118                  4  4.5   4.5  9.65   
1           2        324          107                  4  4.0   4.5  8.87   
2           3        316          104                  3  3.0   3.5  8.00   
3           4        322          110                  3  3.5   2.5  8.67   
4           5        314          103                  2  2.0   3.0  8.21   

   Research  Chance of Admit   
0         1              0.92  
1         1              0.76  
2         1              0.72  
3         1              0.80  
4         0              0.65

In [ ]:
from pandas_profiling import ProfileReport
pf=ProfileReport(df)

In [ ]:
pf.to_widgets()

In [3]:
df.isnull().sum()

Serial No.           0
GRE Score            0
TOEFL Score          0
University Rating    0
SOP                  0
LOR                  0
CGPA                 0
Research             0
Chance of Admit      0
dtype: int64

In [4]:
df.describe()

Serial No.   GRE Score  TOEFL Score  University Rating         SOP  \
count  400.000000  400.000000   400.000000         400.000000  400.000000   
mean   200.500000  316.807500   107.410000           3.087500    3.400000   
std    115.614301   11.473646     6.069514           1.143728    1.006869   
min      1.000000  290.000000    92.000000           1.000000    1.000000   
25%    100.750000  308.000000   103.000000           2.000000    2.500000   
50%    200.500000  317.000000   107.000000           3.000000    3.500000   
75%    300.250000  325.000000   112.000000           4.000000    4.000000   
max    400.000000  340.000000   120.000000           5.000000    5.000000   

             LOR         CGPA    Research  Chance of Admit   
count  400.000000  400.000000  400.000000        400.000000  
mean     3.452500    8.598925    0.547500          0.724350  
std      0.898478    0.596317    0.498362          0.142609  
min      1.000000    6.800000    0.000000          0.340000  
25%      3.000000    8.170000    0.000000          0.640000  
50%      3.500000    8.610000    1.000000          0.730000  
75%      4.000000    9.062500    1.000000          0.830000  
max      5.000000    9.920000    1.000000          0.970000

In [5]:
df.drop(columns=["Serial No."],inplace=True)

In [6]:
df.head(3)

GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  Research  \
0        337          118                  4  4.5   4.5  9.65         1   
1        324          107                  4  4.0   4.5  8.87         1   
2        316          104                  3  3.0   3.5  8.00         1   

   Chance of Admit   
0              0.92  
1              0.76  
2              0.72

In [7]:
import statsmodels.formula.api as snf
lm=snf.ols(formula='Chance of Admit~ GRE_Score+SOP+CGPA+Research',data=df).fit()
lm.summary()

ModuleNotFoundError: No module named 'statsmodels'

In [8]:
x=df.iloc[:,:-1]
y=df.iloc[:,-1]

In [9]:
x.head(3)

GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  Research
0        337          118                  4  4.5   4.5  9.65         1
1        324          107                  4  4.0   4.5  8.87         1
2        316          104                  3  3.0   3.5  8.00         1

In [10]:
y.head(3)

0    0.92
1    0.76
2    0.72
Name: Chance of Admit , dtype: float64

In [11]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()

In [12]:
scaler.fit_transform(x,y)

array([[ 1.76210664,  1.74697064,  0.79882862, ...,  1.16732114,
         1.76481828,  0.90911166],
       [ 0.62765641, -0.06763531,  0.79882862, ...,  1.16732114,
         0.45515126,  0.90911166],
       [-0.07046681, -0.56252785, -0.07660001, ...,  0.05293342,
        -1.00563118,  0.90911166],
       ...,
       [ 1.15124883,  1.41704229,  0.79882862, ...,  1.16732114,
         1.42900622,  0.90911166],
       [-0.41952842, -0.72749202, -0.07660001, ...,  0.61012728,
         0.30403584, -1.09997489],
       [ 1.41304503,  1.58200646,  0.79882862, ...,  0.61012728,
         1.78160888,  0.90911166]])

In [15]:
arr=scaler.fit_transform(x,y)

In [16]:
arr

array([[ 1.76210664,  1.74697064,  0.79882862, ...,  1.16732114,
         1.76481828,  0.90911166],
       [ 0.62765641, -0.06763531,  0.79882862, ...,  1.16732114,
         0.45515126,  0.90911166],
       [-0.07046681, -0.56252785, -0.07660001, ...,  0.05293342,
        -1.00563118,  0.90911166],
       ...,
       [ 1.15124883,  1.41704229,  0.79882862, ...,  1.16732114,
         1.42900622,  0.90911166],
       [-0.41952842, -0.72749202, -0.07660001, ...,  0.61012728,
         0.30403584, -1.09997489],
       [ 1.41304503,  1.58200646,  0.79882862, ...,  0.61012728,
         1.78160888,  0.90911166]])

In [17]:
df1=pd.DataFrame(arr)

In [25]:
df1=pd.DataFrame(arr,columns=["GRE Score","TOEFL Score","University Rating","SOP","LOR","CGPA","Research"])

In [19]:
df1.shape

(400, 7)

In [20]:
df.shape

(400, 8)

In [21]:
df1.head()

0         1         2         3         4         5         6
0  1.762107  1.746971  0.798829  1.093864  1.167321  1.764818  0.909112
1  0.627656 -0.067635  0.798829  0.596653  1.167321  0.455151  0.909112
2 -0.070467 -0.562528 -0.076600 -0.397769  0.052933 -1.005631  0.909112
3  0.453126  0.427257 -0.076600  0.099442 -1.061454  0.119339  0.909112
4 -0.244998 -0.727492 -0.952029 -1.392191 -0.504260 -0.653029 -1.099975

In [22]:
pf1=df1.profile_report()
pf1.to_widgets()

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render widgets:   0%|          | 0/1 [00:00<?, ?it/s]

In [23]:
df1.describe()

0             1             2             3             4  \
count  4.000000e+02  4.000000e+02  4.000000e+02  4.000000e+02  4.000000e+02   
mean  -3.785861e-16  5.412337e-16  7.147061e-16  1.859624e-16 -3.019807e-16   
std    1.001252e+00  1.001252e+00  1.001252e+00  1.001252e+00  1.001252e+00   
min   -2.339367e+00 -2.542098e+00 -1.827457e+00 -2.386613e+00 -2.733036e+00   
25%   -7.685900e-01 -7.274920e-01 -9.520286e-01 -8.949798e-01 -5.042604e-01   
50%    1.679859e-02 -6.763531e-02 -7.660001e-02  9.944220e-02  5.293342e-02   
75%    7.149218e-01  7.571856e-01  7.988286e-01  5.966532e-01  6.101273e-01   
max    2.023903e+00  2.076899e+00  1.674257e+00  1.591075e+00  1.724515e+00   

                  5             6  
count  4.000000e+02  4.000000e+02  
mean   8.076873e-16  2.942091e-17  
std    1.001252e+00  1.001252e+00  
min   -3.020504e+00 -1.099975e+00  
25%   -7.201909e-01 -1.099975e+00  
50%    1.859559e-02  9.091117e-01  
75%    7.783704e-01  9.091117e-01  
max    2.218165e+00  9.091117e-01

In [24]:
df.describe()

GRE Score  TOEFL Score  University Rating         SOP        LOR   \
count  400.000000   400.000000         400.000000  400.000000  400.000000   
mean   316.807500   107.410000           3.087500    3.400000    3.452500   
std     11.473646     6.069514           1.143728    1.006869    0.898478   
min    290.000000    92.000000           1.000000    1.000000    1.000000   
25%    308.000000   103.000000           2.000000    2.500000    3.000000   
50%    317.000000   107.000000           3.000000    3.500000    3.500000   
75%    325.000000   112.000000           4.000000    4.000000    4.000000   
max    340.000000   120.000000           5.000000    5.000000    5.000000   

             CGPA    Research  Chance of Admit   
count  400.000000  400.000000        400.000000  
mean     8.598925    0.547500          0.724350  
std      0.596317    0.498362          0.142609  
min      6.800000    0.000000          0.340000  
25%      8.170000    0.000000          0.640000  
50%      8.610000    1.000000          0.730000  
75%      9.062500    1.000000          0.830000  
max      9.920000    1.000000          0.970000

In [25]:
arr.shape

(400, 7)

In [26]:
from statsmodels.stats.outliers_influence import variance_inflation_factor
[variance_inflation_factor(arr,i) for i in range(arr.shape[1])]

[4.615516166781608,
 4.288959013746899,
 2.9196056618253414,
 3.0755037219543464,
 2.431258484869441,
 5.207402545736424,
 1.5433119011502883]

In [27]:
arr.shape

(400, 7)

In [28]:
arr.shape[1]

7

In [29]:
vif_df=pd.DataFrame()

In [30]:
vif_df['vif']=[variance_inflation_factor(arr,i) for i in range(arr.shape[1])]
vif_df["feature"]=x.columns

In [31]:
vif_df

vif            feature
0  4.615516          GRE Score
1  4.288959        TOEFL Score
2  2.919606  University Rating
3  3.075504                SOP
4  2.431258               LOR 
5  5.207403               CGPA
6  1.543312           Research

In [32]:
x_train,x_test,y_train,y_test=train_test_split(arr,y,test_size=0.15,random_state=50)

In [33]:
x_train

array([[ 0.1913294 , -0.23259949, -0.07660001, ..., -1.06145431,
        -0.45154128,  0.90911166],
       [ 0.88945262,  0.92214975, -0.07660001, ..., -0.50426044,
         0.10254861,  0.90911166],
       [ 0.62765641, -0.06763531,  0.79882862, ...,  1.16732114,
         0.45515126,  0.90911166],
       ...,
       [-1.11765165, -0.72749202,  1.67425725, ...,  0.61012728,
         0.0689674 , -1.09997489],
       [ 0.62765641,  0.42725722, -0.07660001, ...,  0.05293342,
         0.74059151,  0.90911166],
       [ 1.06398342,  1.91193482,  0.79882862, ...,  1.16732114,
         0.94207874,  0.90911166]])

In [34]:
lr= LinearRegression()

In [35]:
lr.fit(x_train,y_train)

LinearRegression()

In [36]:
import pickle

In [37]:
pickle.dump(lr,open('addmision_lr_model_pickle','wb'))

In [38]:
df.head(3)

GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  Research  \
0        337          118                  4  4.5   4.5  9.65         1   
1        324          107                  4  4.0   4.5  8.87         1   
2        316          104                  3  3.0   3.5  8.00         1   

   Chance of Admit   
0              0.92  
1              0.76  
2              0.72

In [39]:
# the output will wrong as we have done standardscaler
lr.predict([[337 ,118 ,4 ,4.5 ,4.5 ,9.65,1]])

array([10.14784928])

In [40]:
scaler.transform([[337 ,118 ,4 ,4.5 ,4.5 ,9.65,1]])

C:\Users\win11\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


array([[1.76210664, 1.74697064, 0.79882862, 1.09386422, 1.16732114,
        1.76481828, 0.90911166]])

In [41]:
lr.predict([[1.76210664, 1.74697064, 0.79882862, 1.09386422, 1.16732114,
        1.76481828, 0.90911166]])

array([0.95498534])

In [42]:
test1=scaler.transform([[337 ,118 ,4 ,4.5 ,4.5 ,9.65,1]])

C:\Users\win11\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


In [43]:
model=pickle.load(open('addmision_lr_model_pickle','rb'))

In [44]:
model.predict(test1)

array([0.95498534])

In [45]:
lr.score(arr,y)  # score of train

0.8029372303954766

In [46]:
lr.score(x_test,y_test) # score of test

0.8094223364432864

In [47]:
# let calculate adjusted R-square--

def adj_r2(x,y):
    r2=lr.score(x,y)
    n=x.shape[0]
    p=x.shape[1]
    adjusted_r2=1-(1-r2)*(n-1)/(n-p-1)
    return adjusted_r2

In [48]:
adj_r2(x_test,y_test)

0.7837676509644981

In [49]:
x_train.corr()

AttributeError: 'numpy.ndarray' object has no attribute 'corr'

In [50]:
import seaborn as sns

In [51]:
df1

0         1         2         3         4         5         6
0    1.762107  1.746971  0.798829  1.093864  1.167321  1.764818  0.909112
1    0.627656 -0.067635  0.798829  0.596653  1.167321  0.455151  0.909112
2   -0.070467 -0.562528 -0.076600 -0.397769  0.052933 -1.005631  0.909112
3    0.453126  0.427257 -0.076600  0.099442 -1.061454  0.119339  0.909112
4   -0.244998 -0.727492 -0.952029 -1.392191 -0.504260 -0.653029 -1.099975
..        ...       ...       ...       ...       ...       ...       ...
395  0.627656  0.427257 -0.076600  0.099442  0.052933  0.740592  0.909112
396  0.714922 -0.067635 -0.076600 -0.397769  0.052933  0.858126  0.909112
397  1.151249  1.417042  0.798829  1.591075  1.167321  1.429006  0.909112
398 -0.419528 -0.727492 -0.076600  0.099442  0.610127  0.304036 -1.099975
399  1.413045  1.582006  0.798829  1.591075  0.610127  1.781609  0.909112

[400 rows x 7 columns]

In [52]:
lr.intercept_

0.723343778932555

In [53]:
lr.coef_

array([ 0.01964946,  0.01673022,  0.00375235, -0.00218183,  0.02229053,
        0.07364405,  0.01230924])

### Using Lasso, Ridge and Elasticnet in Linear Regression

In [54]:
from sklearn.linear_model import Ridge,Lasso,ElasticNet
from sklearn.linear_model import LassoCV,RidgeCV,ElasticNetCV

In [55]:
lassocv = LassoCV(cv=5, max_iter=20000000,normalize=True)
lassocv.fit(x_train,y_train)

C:\Users\win11\anaconda3\lib\site-packages\sklearn\linear_model\_base.py:141: FutureWarning: 'normalize' was deprecated in version 1.0 and will be removed in 1.2.
If you wish to scale the data, use Pipeline with a StandardScaler in a preprocessing stage. To reproduce the previous behavior:

from sklearn.pipeline import make_pipeline

model = make_pipeline(StandardScaler(with_mean=False), Lasso())

If you wish to pass a sample_weight parameter, you need to pass it as a fit parameter to each step of the pipeline as follows:

kwargs = {s[0] + '__sample_weight': sample_weight for s in model.steps}
model.fit(X, y, **kwargs)

Set parameter alpha to: original_alpha * np.sqrt(n_samples). 
  warnings.warn(


LassoCV(cv=5, max_iter=20000000, normalize=True)

In [56]:
lassocv.alpha_

7.876538580622378e-05

In [57]:
lasso=Lasso(alpha=lassocv.alpha_)
lasso.fit(x_train,y_train)

Lasso(alpha=7.876538580622378e-05)

In [58]:
lasso.score(x_test,y_test)

0.8093912273959238

In [59]:
df.head(2)

GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  Research  \
0        337          118                  4  4.5   4.5  9.65         1   
1        324          107                  4  4.0   4.5  8.87         1   

   Chance of Admit   
0              0.92  
1              0.76

In [60]:
lasso.predict([[337 ,118 ,4 ,4.5 ,4.5 ,9.65 ,1]])

array([10.14987955])

In [61]:
t=scaler.transform([[337 ,118 ,4 ,4.5 ,4.5 ,9.65 ,1]])
t

C:\Users\win11\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


array([[1.76210664, 1.74697064, 0.79882862, 1.09386422, 1.16732114,
        1.76481828, 0.90911166]])

In [62]:
lasso.predict(t)

array([0.95485279])

In [63]:
ridgecv=RidgeCV(alphas=(0.1, 1.0, 10.0),cv=10,normalize=True)
ridgecv.fit(x_train,y_train)  
## alpha and lambda are same thing
## in theory it is lambda and in scikit it is alpha

C:\Users\win11\anaconda3\lib\site-packages\sklearn\linear_model\_base.py:141: FutureWarning: 'normalize' was deprecated in version 1.0 and will be removed in 1.2.
If you wish to scale the data, use Pipeline with a StandardScaler in a preprocessing stage. To reproduce the previous behavior:

from sklearn.pipeline import make_pipeline

model = make_pipeline(StandardScaler(with_mean=False), Ridge())

If you wish to pass a sample_weight parameter, you need to pass it as a fit parameter to each step of the pipeline as follows:

kwargs = {s[0] + '__sample_weight': sample_weight for s in model.steps}
model.fit(X, y, **kwargs)

Set parameter alpha to: original_alpha * n_samples. 
  warnings.warn(
C:\Users\win11\anaconda3\lib\site-packages\sklearn\linear_model\_base.py:141: FutureWarning: 'normalize' was deprecated in version 1.0 and will be removed in 1.2.
If you wish to scale the data, use Pipeline with a StandardScaler in a preprocessing stage. To reproduce the previous behavior:

from sklea

RidgeCV(alphas=array([ 0.1,  1. , 10. ]), cv=10, normalize=True)

In [64]:
ridgecv.alpha_

0.1

In [65]:
ridge_lr=Ridge(alpha=ridgecv.alpha_)
ridge_lr.fit(x_train,y_train)

Ridge(alpha=0.1)

In [66]:
ridge_lr.score(x_test,y_test)

0.8094719085142769

In [67]:
## Elastic =lasso+ridge (combination of both)

elastic=ElasticNetCV(alphas=None,cv=10)
elastic.fit(x_train,y_train)

ElasticNetCV(cv=10)

In [68]:
elastic.alpha_  # it is lambda

0.0016669924023373828

In [69]:
elastic.l1_ratio # it is actually alpha in elastic net

0.5

In [70]:
elastic.l1_ratio_  # it is actually alpha in elastic net

0.5

In [71]:
elastic_lr=ElasticNet(alpha=elastic.alpha_,l1_ratio=elastic.l1_ratio_)

In [72]:
elastic_lr.fit(x_train,y_train)

ElasticNet(alpha=0.0016669924023373828)

In [73]:
elastic_lr.score(x_test,y_test)

0.8101969646906351

In [74]:
t=scaler.transform([[337 ,118 ,4 ,4.5 ,4.5 ,9.65 ,1]])
t

C:\Users\win11\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


array([[1.76210664, 1.74697064, 0.79882862, 1.09386422, 1.16732114,
        1.76481828, 0.90911166]])

In [75]:
elastic_lr.predict(t)

array([0.95343197])

In [76]:
df.head(3)

GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  Research  \
0        337          118                  4  4.5   4.5  9.65         1   
1        324          107                  4  4.0   4.5  8.87         1   
2        316          104                  3  3.0   3.5  8.00         1   

   Chance of Admit   
0              0.92  
1              0.76  
2              0.72

In [77]:
a=scaler.transform([[324 ,107 ,4 ,4.0 ,4.5 ,8.87 ,1]])
a

C:\Users\win11\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


array([[ 0.62765641, -0.06763531,  0.79882862,  0.59665321,  1.16732114,
         0.45515126,  0.90911166]])

In [78]:
elastic_lr.predict(a)

array([0.80577028])

In [79]:
lasso.predict(a)

array([0.80683514])

In [80]:
ridge_lr.predict(a)

array([0.80697264])

In [81]:
lr.predict(a)

array([0.80697089])

In [82]:
lr

LinearRegression()

In [83]:
import pickle
pickle.dump(elastic_lr,open("elastic_model.pkl",'wb'))