In [1]:
import numpy as np
import pandas as pd

In [2]:
from sklearn.model_selection import GridSearchCV, train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, roc_auc_score, roc_curve

In [3]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler

In [28]:
data=pd.read_csv("H:\DataSet_csv\winequality-red.csv",sep=";")

In [29]:
data.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5  
3      9.8        6  
4      9.4        5

In [30]:
x=data.iloc[:,:-1]
y=data.iloc[:,-1]

In [31]:
x

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.4             0.700         0.00             1.9      0.076   
1               7.8             0.880         0.00             2.6      0.098   
2               7.8             0.760         0.04             2.3      0.092   
3              11.2             0.280         0.56             1.9      0.075   
4               7.4             0.700         0.00             1.9      0.076   
...             ...               ...          ...             ...        ...   
1594            6.2             0.600         0.08             2.0      0.090   
1595            5.9             0.550         0.10             2.2      0.062   
1596            6.3             0.510         0.13             2.3      0.076   
1597            5.9             0.645         0.12             2.0      0.075   
1598            6.0             0.310         0.47             3.6      0.067   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    11.0                  34.0  0.99780  3.51       0.56   
1                    25.0                  67.0  0.99680  3.20       0.68   
2                    15.0                  54.0  0.99700  3.26       0.65   
3                    17.0                  60.0  0.99800  3.16       0.58   
4                    11.0                  34.0  0.99780  3.51       0.56   
...                   ...                   ...      ...   ...        ...   
1594                 32.0                  44.0  0.99490  3.45       0.58   
1595                 39.0                  51.0  0.99512  3.52       0.76   
1596                 29.0                  40.0  0.99574  3.42       0.75   
1597                 32.0                  44.0  0.99547  3.57       0.71   
1598                 18.0                  42.0  0.99549  3.39       0.66   

      alcohol  
0         9.4  
1         9.8  
2         9.8  
3         9.8  
4         9.4  
...       ...  
1594     10.5  
1595     11.2  
1596     11.0  
1597     10.2  
1598     11.0  

[1599 rows x 11 columns]

In [32]:
y

0       5
1       5
2       5
3       6
4       5
       ..
1594    5
1595    6
1596    6
1597    5
1598    6
Name: quality, Length: 1599, dtype: int64

In [33]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=101)

In [18]:
knn=KNeighborsClassifier()

In [19]:
knn.fit(x_train,y_train)

KNeighborsClassifier()

In [20]:
knn.score(x_test,y_test)

0.5

### using GridSearchCV -Hyperparmeter in KNN

In [25]:
from sklearn.model_selection import GridSearchCV

In [43]:
pram={
    'n_neighbors':[3,5,7,9,11,13,15,17,21],
    'weights':['uniform', 'distance'],
    'algorithm':['auto', 'ball_tree', 'kd_tree', 'brute'],
    'p':[1,2],
    'leaf_size':[10,15,20,25,30,35,40,50,55,60,65]
}

In [44]:
grid_cv_model=GridSearchCV(estimator=knn,param_grid=pram)

In [45]:
grid_cv_model.fit(x_train,y_train)

GridSearchCV(estimator=KNeighborsClassifier(n_neighbors=15),
             param_grid={'algorithm': ['auto', 'ball_tree', 'kd_tree', 'brute'],
                         'leaf_size': [10, 15, 20, 25, 30, 35, 40, 50, 55, 60,
                                       65],
                         'n_neighbors': [3, 5, 7, 9, 11, 13, 15, 17, 21],
                         'p': [1, 2], 'weights': ['uniform', 'distance']})

In [46]:
grid_cv_model.best_params_

{'algorithm': 'auto',
 'leaf_size': 10,
 'n_neighbors': 21,
 'p': 1,
 'weights': 'distance'}

In [47]:
knn=KNeighborsClassifier(algorithm='auto',n_neighbors=15,leaf_size=10,p=1,weights='distance')

In [48]:
knn.fit(x_train,y_train)

KNeighborsClassifier(leaf_size=10, n_neighbors=15, p=1, weights='distance')

In [49]:
knn.score(x_test,y_test)

0.634375

In [52]:
import pickle
pickle.dump(knn,open("knn.pkl",'wb'))

In [53]:
x_test.iloc[0]

fixed acidity            8.3000
volatile acidity         0.7800
citric acid              0.1000
residual sugar           2.6000
chlorides                0.0810
free sulfur dioxide     45.0000
total sulfur dioxide    87.0000
density                  0.9983
pH                       3.4800
sulphates                0.5300
alcohol                 10.0000
Name: 678, dtype: float64

In [55]:
knn.predict([x_test.iloc[0]])

C:\Users\win11\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(


array([5], dtype=int64)

In [65]:
knn.predict([[8.30,0.78,0.10,2.6,0.08,45.00,87.00,0.9983,3.48,0.53,10.00]])

C:\Users\win11\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(


array([5], dtype=int64)

## SVM --

In [26]:
# SVC
from sklearn.svm import SVC

In [34]:
svc=SVC()
svc.fit(x_train,y_train)

SVC()

In [35]:
svc.score(x_test,y_test)

0.478125

## using GridSearchCV -Hyperparmeter in SVM

In [97]:
params={
    "kernel":['linear', 'poly', 'rbf', 'sigmoid'],
      "C":[.1,.2,.5,.7,1,3,5,7,10,25,50,100,250,500],
    "gamma":[.001,.1,.4,.004,.003]
    
}

In [98]:
svm_grid=GridSearchCV(svc,param_grid=params,verbose=4)

In [ ]:
#svm_grid.fit(x_train,y_train) # it will take very much time

Fitting 5 folds for each of 280 candidates, totalling 1400 fits
[CV 1/5] END .C=0.1, gamma=0.001, kernel=linear;, score=0.605 total time=   0.2s
[CV 2/5] END .C=0.1, gamma=0.001, kernel=linear;, score=0.586 total time=   0.3s
[CV 3/5] END .C=0.1, gamma=0.001, kernel=linear;, score=0.559 total time=   0.8s
[CV 4/5] END .C=0.1, gamma=0.001, kernel=linear;, score=0.555 total time=   0.5s
[CV 5/5] END .C=0.1, gamma=0.001, kernel=linear;, score=0.569 total time=   0.9s
[CV 1/5] END ...C=0.1, gamma=0.001, kernel=poly;, score=0.484 total time=   0.1s
[CV 2/5] END ...C=0.1, gamma=0.001, kernel=poly;, score=0.496 total time=   0.1s
[CV 3/5] END ...C=0.1, gamma=0.001, kernel=poly;, score=0.465 total time=   0.2s
[CV 4/5] END ...C=0.1, gamma=0.001, kernel=poly;, score=0.488 total time=   0.2s
[CV 5/5] END ...C=0.1, gamma=0.001, kernel=poly;, score=0.529 total time=   0.2s
[CV 1/5] END ....C=0.1, gamma=0.001, kernel=rbf;, score=0.480 total time=   0.1s
[CV 2/5] END ....C=0.1, gamma=0.001, kernel=r

In [89]:
svm_grid.best_params_

{'kernel': 'linear'}

In [91]:
svm_1=SVC(kernel="linear")

In [92]:
svm_1.fit(x_train,y_train)

SVC(kernel='linear')

In [93]:
svm_1.score(x_test,y_test)

0.578125

## SVR

In [4]:
df=pd.read_csv("H:\DataSet_csv\Admission_Predict.csv")

In [6]:
df.head()

Serial No.  GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  \
0           1        337          118                  4  4.5   4.5  9.65   
1           2        324          107                  4  4.0   4.5  8.87   
2           3        316          104                  3  3.0   3.5  8.00   
3           4        322          110                  3  3.5   2.5  8.67   
4           5        314          103                  2  2.0   3.0  8.21   

   Research  Chance of Admit   
0         1              0.92  
1         1              0.76  
2         1              0.72  
3         1              0.80  
4         0              0.65

In [46]:
x1=df.iloc[:,:-1]
y1=df.iloc[:,-1]

In [47]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=20)

In [48]:
from sklearn.svm import SVR

In [49]:
svr=SVR()

In [50]:
svr.fit(x_train,y_train)

SVR()

In [51]:
svr.score(x_test,y_test)

0.18268717671930623

In [52]:
df.isnull().sum()

Serial No.           0
GRE Score            0
TOEFL Score          0
University Rating    0
SOP                  0
LOR                  0
CGPA                 0
Research             0
Chance of Admit      0
dtype: int64

In [53]:
df["GRE Score"]=df["GRE Score"].fillna(df["GRE Score"].mean())

In [54]:
from sklearn.metrics import r2_score
r2_score(y_test,svr.predict(x_test))

0.18268717671930623

In [55]:
svr.score(x_test,y_test)

0.18268717671930623

# Stacking

In [56]:
 svm and knn insided stacking

SyntaxError: invalid syntax (3243722531.py, line 1)

In [60]:

data=pd.read_csv("H:\DataSet_csv\winequality-red.csv",sep=';')

In [61]:
data.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5  
3      9.8        6  
4      9.4        5

In [62]:
x=data.iloc[:,:-1]
y=data.iloc[:,-1]

In [71]:
train,val_train,test,val_test=train_test_split(x,y,test_size=0.50,random_state=30)

In [72]:
x_train,x_test,y_train,y_test=train_test_split(train,test,test_size=0.15,random_state=35)

In [73]:
data["quality"].unique()

array([5, 6, 7, 4, 8, 3], dtype=int64)

In [74]:
knn=KNeighborsClassifier()
knn.fit(x_train,y_train)

KNeighborsClassifier()

In [75]:
knn.score(x_test,y_test)

0.525

In [76]:
svc=SVC()
svc.fit(x_train,y_train)

SVC()

In [77]:
svc.score(x_train,y_train)

0.5084621044885945

In [78]:
prediction_knn=knn.predict(val_train)
prediction_svc=svc.predict(val_train)

In [80]:
input3=np.column_stack((prediction_knn,prediction_svc))
input3

array([[7, 6],
       [4, 6],
       [5, 6],
       ...,
       [6, 6],
       [6, 6],
       [6, 5]], dtype=int64)

In [81]:
output=val_test

In [82]:
output

1147    7
659     4
871     5
1333    5
1411    6
       ..
1073    6
200     7
942     7
1106    6
1329    6
Name: quality, Length: 800, dtype: int64

In [87]:
from sklearn.ensemble import RandomForestClassifier

In [88]:
rf=RandomForestClassifier()

In [91]:
rf.fit(input3,output)

RandomForestClassifier()

In [93]:
rf.predict(input3)

array([7, 4, 5, 5, 6, 5, 6, 6, 5, 5, 5, 5, 6, 6, 7, 6, 5, 6, 6, 6, 6, 6,
       6, 5, 6, 6, 6, 5, 5, 6, 5, 6, 6, 5, 6, 6, 6, 6, 5, 7, 5, 6, 6, 5,
       5, 6, 6, 6, 6, 6, 5, 5, 6, 6, 5, 5, 6, 5, 5, 5, 6, 5, 6, 5, 7, 5,
       5, 6, 5, 4, 5, 5, 5, 5, 6, 6, 6, 5, 5, 6, 6, 6, 6, 6, 5, 5, 5, 6,
       6, 5, 5, 7, 5, 6, 6, 4, 5, 7, 5, 5, 6, 5, 5, 7, 6, 6, 6, 5, 5, 5,
       5, 5, 5, 6, 7, 6, 6, 6, 5, 5, 6, 6, 6, 6, 5, 5, 6, 6, 6, 6, 5, 5,
       5, 5, 7, 5, 5, 5, 7, 7, 5, 5, 5, 5, 6, 5, 5, 5, 5, 7, 5, 5, 5, 6,
       5, 5, 6, 6, 5, 5, 5, 6, 6, 5, 6, 5, 5, 5, 6, 7, 6, 6, 6, 6, 5, 5,
       5, 5, 6, 6, 5, 5, 6, 5, 5, 6, 5, 7, 6, 7, 5, 5, 6, 5, 7, 5, 6, 5,
       5, 6, 7, 5, 6, 5, 6, 6, 6, 7, 6, 6, 6, 5, 6, 5, 5, 5, 5, 5, 7, 5,
       6, 6, 7, 5, 6, 4, 6, 5, 5, 5, 5, 6, 6, 7, 5, 5, 5, 6, 5, 6, 5, 6,
       5, 5, 5, 6, 6, 5, 6, 5, 5, 7, 5, 6, 5, 5, 5, 5, 5, 6, 6, 5, 6, 6,
       6, 5, 6, 6, 6, 6, 5, 5, 6, 5, 5, 5, 4, 6, 5, 5, 6, 5, 5, 6, 6, 6,
       6, 6, 5, 7, 5, 5, 6, 7, 5, 6, 5, 6, 5, 6, 5,

In [94]:
rf.score(input3,y_test)

ValueError: Found input variables with inconsistent numbers of samples: [240, 800]