In [1]:
import pandas as pd

In [2]:
pd.DataFrame({
    "col1" : [1,2,3,4,5],
    "col2" : [45,56,67,34,34],
    "col3" : "sudhansu kumar Sumay Krish naik ineuron"
})

col1  col2                                     col3
0     1    45  sudhansu kumar Sumay Krish naik ineuron
1     2    56  sudhansu kumar Sumay Krish naik ineuron
2     3    67  sudhansu kumar Sumay Krish naik ineuron
3     4    34  sudhansu kumar Sumay Krish naik ineuron
4     5    34  sudhansu kumar Sumay Krish naik ineuron

In [3]:
df = pd.DataFrame({
    "col1" : [1,2,3,4,5],
    "col2" : [45,56,67,34,34],
    "col3" : "sudhansu kumar sumay Krish naik".split()
})

In [4]:
df

col1  col2      col3
0     1    45  sudhansu
1     2    56     kumar
2     3    67     sumay
3     4    34     Krish
4     5    34      naik

In [5]:
df["col4"] = df["col1"] ** 2

In [6]:
df

col1  col2      col3  col4
0     1    45  sudhansu     1
1     2    56     kumar     4
2     3    67     sumay     9
3     4    34     Krish    16
4     5    34      naik    25

In [7]:
df["col5"] = df["col3"].str[0]

In [8]:
df

col1  col2      col3  col4 col5
0     1    45  sudhansu     1    s
1     2    56     kumar     4    k
2     3    67     sumay     9    s
3     4    34     Krish    16    K
4     5    34      naik    25    n

In [9]:
# this is the anothere way to gett square

def test(a):
    return a**2

In [10]:
df["col4_4"] = df["col1"].apply(test)

In [11]:
df

col1  col2      col3  col4 col5  col4_4
0     1    45  sudhansu     1    s       1
1     2    56     kumar     4    k       4
2     3    67     sumay     9    s       9
3     4    34     Krish    16    K      16
4     5    34      naik    25    n      25

In [13]:
# now i have to create a column col_5 in which 
# the in first word should be "s" remain "s" else write "z"
try:
    
    def test_1(a):
        if a=="s":
            return "s"
        else:
            return "z"
except Exception as e:
    print(e)

In [14]:
df["col_6"] = df["col5"].apply(test_1)

In [15]:
df

col1  col2      col3  col4 col5  col4_4 col_6
0     1    45  sudhansu     1    s       1     s
1     2    56     kumar     4    k       4     z
2     3    67     sumay     9    s       9     s
3     4    34     Krish    16    K      16     z
4     5    34      naik    25    n      25     z

In [16]:
df["col_6_of_6"] = df["col5"].apply(lambda a:"s" if a=="s" else "z")

In [17]:
df

col1  col2      col3  col4 col5  col4_4 col_6 col_6_of_6
0     1    45  sudhansu     1    s       1     s          s
1     2    56     kumar     4    k       4     z          z
2     3    67     sumay     9    s       9     s          s
3     4    34     Krish    16    K      16     z          z
4     5    34      naik    25    n      25     z          z

In [18]:
def test_3(a):
    return len(a)

In [20]:
df["co_7"] = df["col3"].apply(test_3)

In [21]:
df

col1  col2      col3  col4 col5  col4_4 col_6 col_6_of_6  co_7
0     1    45  sudhansu     1    s       1     s          s     8
1     2    56     kumar     4    k       4     z          z     5
2     3    67     sumay     9    s       9     s          s     5
3     4    34     Krish    16    K      16     z          z     5
4     5    34      naik    25    n      25     z          z     4

In [26]:
import math

In [28]:
df["col_8"]=df["col2"].apply(math.log)

In [29]:
df

col1  col2      col3  col4 col5  col4_4 col_6 col_6_of_6  co_7     col_8
0     1    45  sudhansu     1    s       1     s          s     8  3.806662
1     2    56     kumar     4    k       4     z          z     5  4.025352
2     3    67     sumay     9    s       9     s          s     5  4.204693
3     4    34     Krish    16    K      16     z          z     5  3.526361
4     5    34      naik    25    n      25     z          z     4  3.526361

# Numpy

In [2]:
import numpy as np

In [3]:
# arrray are equivalient to list

SyntaxError: invalid syntax (1651103922.py, line 1)

In [4]:
l=["sumay",1,2,3,4]

In [5]:
type(l)

list

In [6]:
np.array(l)

array(['sumay', '1', '2', '3', '4'], dtype='<U11')

In [7]:
type(np.array(l))

numpy.ndarray

In [8]:
np.array([1,2,3,4.0])

array([1., 2., 3., 4.])

In [9]:
np.array([1,2,3,4.2])

array([1. , 2. , 3. , 4.2])

In [10]:
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [11]:
a = np.array([[1,2],[3,4]])

In [12]:
a

array([[1, 2],
       [3, 4]])

In [13]:
a[1]

array([3, 4])

In [14]:
a[1][1]

4

In [15]:
np.array([1,2,3,4],ndmin=0)

array([1, 2, 3, 4])

In [16]:
np.array([1,2,3,4],ndmin=2)

array([[1, 2, 3, 4]])

In [17]:
np.array([1,2,3,4],ndmin=3)

array([[[1, 2, 3, 4]]])

In [18]:
np.array([1,2,3,4],ndmin=4)

array([[[[1, 2, 3, 4]]]])

In [19]:
a2=np.array([1,2,3,4],ndmin=4)

In [20]:
a2

array([[[[1, 2, 3, 4]]]])

In [21]:
a2[0][0]

array([[1, 2, 3, 4]])

In [22]:
a2[0][0][0][0]

1

In [23]:
np.asarray([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [24]:
np.asanyarray([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [25]:
np.mat([1,2,3,4,5])

matrix([[1, 2, 3, 4, 5]])

In [26]:
# Array can have the nth given dimension whereas matrix have minimum 2D

In [27]:
a=[1,2,3,4,5,6]
np.asarray(a)

array([1, 2, 3, 4, 5, 6])

In [28]:
np.mat(a)

matrix([[1, 2, 3, 4, 5, 6]])

In [29]:
np.asanyarray(a)

array([1, 2, 3, 4, 5, 6])

In [30]:
np.asanyarray(np.mat(a))

matrix([[1, 2, 3, 4, 5, 6]])

In [31]:
np.fromfunction(lambda i,j : i==j, (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [32]:
np.fromfunction(lambda i,j : i==j, (3,4))

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False]])

In [33]:
np.fromfunction(lambda i,j : i==j, (2,3))

array([[ True, False, False],
       [False,  True, False]])

In [34]:
np.fromfunction(lambda i,j : i*j, (4,4))

array([[0., 0., 0., 0.],
       [0., 1., 2., 3.],
       [0., 2., 4., 6.],
       [0., 3., 6., 9.]])

In [35]:
np.fromfunction(lambda i,j : i*j, (4,4), dtype = int)

array([[0, 0, 0, 0],
       [0, 1, 2, 3],
       [0, 2, 4, 6],
       [0, 3, 6, 9]])

In [36]:
# Matrix is sub-class of array

In [46]:
b=["raja","hi",[1,2,3]]
np.asanyarray(b)

C:\Users\win11\AppData\Local\Temp\ipykernel_21968\3237831660.py:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  np.asanyarray(b)


array(['raja', 'hi', list([1, 2, 3])], dtype=object)

In [48]:
np.fromfunction(lambda i,j,z : i*j*z, (3,3,3), dtype = int)

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 1, 2],
        [0, 2, 4]],

       [[0, 0, 0],
        [0, 2, 4],
        [0, 4, 8]]])

In [49]:
np.fromfunction(lambda i,j,z : i*j*z, (3,3,2), dtype =int)

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 1],
        [0, 2]],

       [[0, 0],
        [0, 2],
        [0, 4]]])

In [57]:
a=np.fromfunction(lambda i,j,z,p : i*j*z*p, (2,3,4,3), dtype =int)

In [58]:
a

array([[[[ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0]],

        [[ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0]],

        [[ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0]]],


       [[[ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0]],

        [[ 0,  0,  0],
         [ 0,  1,  2],
         [ 0,  2,  4],
         [ 0,  3,  6]],

        [[ 0,  0,  0],
         [ 0,  2,  4],
         [ 0,  4,  8],
         [ 0,  6, 12]]]])

In [60]:
a.size

72

In [59]:
a.ndim

4

In [61]:
a.shape

(2, 3, 4, 3)

In [62]:
a.dtype

dtype('int32')

In [66]:
a=np.fromfunction(lambda i,j : i*j, (4,3), dtype =int)

In [67]:
a

array([[0, 0, 0],
       [0, 1, 2],
       [0, 2, 4],
       [0, 3, 6]])

In [68]:
pd.DataFrame(a)

0  1  2
0  0  0  0
1  0  1  2
2  0  2  4
3  0  3  6

In [69]:
a=np.fromfunction(lambda i,j : i*j, (400,300), dtype =int)

In [71]:
a

array([[     0,      0,      0, ...,      0,      0,      0],
       [     0,      1,      2, ...,    297,    298,    299],
       [     0,      2,      4, ...,    594,    596,    598],
       ...,
       [     0,    397,    794, ..., 117909, 118306, 118703],
       [     0,    398,    796, ..., 118206, 118604, 119002],
       [     0,    399,    798, ..., 118503, 118902, 119301]])

In [70]:
pd.DataFrame(a)

0    1    2     3     4     5     6     7     8     9    ...     290  \
0      0    0    0     0     0     0     0     0     0     0  ...       0   
1      0    1    2     3     4     5     6     7     8     9  ...     290   
2      0    2    4     6     8    10    12    14    16    18  ...     580   
3      0    3    6     9    12    15    18    21    24    27  ...     870   
4      0    4    8    12    16    20    24    28    32    36  ...    1160   
..   ...  ...  ...   ...   ...   ...   ...   ...   ...   ...  ...     ...   
395    0  395  790  1185  1580  1975  2370  2765  3160  3555  ...  114550   
396    0  396  792  1188  1584  1980  2376  2772  3168  3564  ...  114840   
397    0  397  794  1191  1588  1985  2382  2779  3176  3573  ...  115130   
398    0  398  796  1194  1592  1990  2388  2786  3184  3582  ...  115420   
399    0  399  798  1197  1596  1995  2394  2793  3192  3591  ...  115710   

        291     292     293     294     295     296     297     298     299  
0         0       0       0       0       0       0       0       0       0  
1       291     292     293     294     295     296     297     298     299  
2       582     584     586     588     590     592     594     596     598  
3       873     876     879     882     885     888     891     894     897  
4      1164    1168    1172    1176    1180    1184    1188    1192    1196  
..      ...     ...     ...     ...     ...     ...     ...     ...     ...  
395  114945  115340  115735  116130  116525  116920  117315  117710  118105  
396  115236  115632  116028  116424  116820  117216  117612  118008  118404  
397  115527  115924  116321  116718  117115  117512  117909  118306  118703  
398  115818  116216  116614  117012  117410  117808  118206  118604  119002  
399  116109  116508  116907  117306  117705  118104  118503  118902  119301  

[400 rows x 300 columns]

In [73]:
np.random.rand(100,4)

array([[0.70995354, 0.02914574, 0.19373944, 0.9180294 ],
       [0.36341738, 0.72976424, 0.54336466, 0.16357802],
       [0.00667308, 0.50542201, 0.42981313, 0.1988347 ],
       [0.14627755, 0.11549932, 0.51853082, 0.51961159],
       [0.86543176, 0.87363709, 0.98240817, 0.61627436],
       [0.55500738, 0.80359658, 0.26286531, 0.57055357],
       [0.80708663, 0.41751694, 0.28295557, 0.41241686],
       [0.89578459, 0.84318626, 0.59709483, 0.50363075],
       [0.74235067, 0.7366551 , 0.98718921, 0.07635639],
       [0.7900352 , 0.47640524, 0.78014908, 0.92049889],
       [0.45960424, 0.37961488, 0.54720164, 0.20595418],
       [0.80255512, 0.31345074, 0.75428257, 0.19741735],
       [0.09429762, 0.56939948, 0.74416373, 0.94657062],
       [0.28737548, 0.993427  , 0.96804127, 0.31644429],
       [0.58033464, 0.92810123, 0.22923413, 0.61372205],
       [0.5713556 , 0.91092976, 0.96827075, 0.79538088],
       [0.99182922, 0.81781924, 0.77231876, 0.52381628],
       [0.100918  , 0.71560338,

In [84]:
np.random.randint(5,50)

20

In [89]:
np.random.randn(4,5)

array([[ 0.22894465, -0.42646048, -1.27562582,  0.29325541,  1.57765389],
       [ 0.58476686, -0.99010262,  0.85709646, -0.39824934, -0.4846553 ],
       [ 1.13658915,  0.26247921,  2.35544467,  1.35720205, -0.16266424],
       [-0.1437568 , -2.01975142,  0.05043799, -0.83109515,  0.56108625]])

In [90]:
pd.DataFrame(np.random.randn(4,5))

0         1         2         3         4
0  0.190405 -0.480095 -0.083191  0.136720  1.109273
1 -0.357326  1.564821  1.260428  0.528554  1.213559
2  1.663981 -0.213075  0.579968 -1.204549 -0.146163
3 -0.028711  0.824192 -0.806078 -0.371033 -0.465836

In [ ]:
np.fromfunction(lambda i,j,z : i*j*z, (3,3,2), dtype =int)

In [97]:
a=np.fromfunction(lambda i,j,z : i*j*z, (4,5,6), dtype =int)

In [98]:
a

array([[[ 0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0]],

       [[ 0,  0,  0,  0,  0,  0],
        [ 0,  1,  2,  3,  4,  5],
        [ 0,  2,  4,  6,  8, 10],
        [ 0,  3,  6,  9, 12, 15],
        [ 0,  4,  8, 12, 16, 20]],

       [[ 0,  0,  0,  0,  0,  0],
        [ 0,  2,  4,  6,  8, 10],
        [ 0,  4,  8, 12, 16, 20],
        [ 0,  6, 12, 18, 24, 30],
        [ 0,  8, 16, 24, 32, 40]],

       [[ 0,  0,  0,  0,  0,  0],
        [ 0,  3,  6,  9, 12, 15],
        [ 0,  6, 12, 18, 24, 30],
        [ 0,  9, 18, 27, 36, 45],
        [ 0, 12, 24, 36, 48, 60]]])

In [103]:
a.reshape(12,10)

array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  1,  2,  3],
       [ 4,  5,  0,  2,  4,  6,  8, 10,  0,  3],
       [ 6,  9, 12, 15,  0,  4,  8, 12, 16, 20],
       [ 0,  0,  0,  0,  0,  0,  0,  2,  4,  6],
       [ 8, 10,  0,  4,  8, 12, 16, 20,  0,  6],
       [12, 18, 24, 30,  0,  8, 16, 24, 32, 40],
       [ 0,  0,  0,  0,  0,  0,  0,  3,  6,  9],
       [12, 15,  0,  6, 12, 18, 24, 30,  0,  9],
       [18, 27, 36, 45,  0, 12, 24, 36, 48, 60]])

In [104]:
pd.DataFrame(a.reshape(12,10))

0   1   2   3   4   5   6   7   8   9
0    0   0   0   0   0   0   0   0   0   0
1    0   0   0   0   0   0   0   0   0   0
2    0   0   0   0   0   0   0   0   0   0
3    0   0   0   0   0   0   0   1   2   3
4    4   5   0   2   4   6   8  10   0   3
5    6   9  12  15   0   4   8  12  16  20
6    0   0   0   0   0   0   0   2   4   6
7    8  10   0   4   8  12  16  20   0   6
8   12  18  24  30   0   8  16  24  32  40
9    0   0   0   0   0   0   0   3   6   9
10  12  15   0   6  12  18  24  30   0   9
11  18  27  36  45   0  12  24  36  48  60

In [106]:
# in 4-D
a.reshape(12,5,2)

array([[[ 0,  0],
        [ 0,  0],
        [ 0,  0],
        [ 0,  0],
        [ 0,  0]],

       [[ 0,  0],
        [ 0,  0],
        [ 0,  0],
        [ 0,  0],
        [ 0,  0]],

       [[ 0,  0],
        [ 0,  0],
        [ 0,  0],
        [ 0,  0],
        [ 0,  0]],

       [[ 0,  0],
        [ 0,  0],
        [ 0,  0],
        [ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 0,  2],
        [ 4,  6],
        [ 8, 10],
        [ 0,  3]],

       [[ 6,  9],
        [12, 15],
        [ 0,  4],
        [ 8, 12],
        [16, 20]],

       [[ 0,  0],
        [ 0,  0],
        [ 0,  0],
        [ 0,  2],
        [ 4,  6]],

       [[ 8, 10],
        [ 0,  4],
        [ 8, 12],
        [16, 20],
        [ 0,  6]],

       [[12, 18],
        [24, 30],
        [ 0,  8],
        [16, 24],
        [32, 40]],

       [[ 0,  0],
        [ 0,  0],
        [ 0,  0],
        [ 0,  3],
        [ 6,  9]],

       [[12, 15],
        [ 0,  6],
        [12, 18],
        [24, 30],
        

In [107]:
b=np.fromfunction(lambda a,b,c : a+b+c,(3,4,5),dtype=int)

In [108]:
b

array([[[0, 1, 2, 3, 4],
        [1, 2, 3, 4, 5],
        [2, 3, 4, 5, 6],
        [3, 4, 5, 6, 7]],

       [[1, 2, 3, 4, 5],
        [2, 3, 4, 5, 6],
        [3, 4, 5, 6, 7],
        [4, 5, 6, 7, 8]],

       [[2, 3, 4, 5, 6],
        [3, 4, 5, 6, 7],
        [4, 5, 6, 7, 8],
        [5, 6, 7, 8, 9]]])

In [110]:
pd.DataFrame(b)

ValueError: Must pass 2-d input. shape=(3, 4, 5)

In [118]:
# -(negative) is a deaufault value---- to take 
b.reshape(12,-1)

array([[0, 1, 2, 3, 4],
       [1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7],
       [1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7],
       [4, 5, 6, 7, 8],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7],
       [4, 5, 6, 7, 8],
       [5, 6, 7, 8, 9]])

In [123]:
pd.DataFrame(b.reshape(5,12))

0   1   2   3   4   5   6   7   8   9   10  11
0   0   1   2   3   4   1   2   3   4   5   2   3
1   4   5   6   3   4   5   6   7   1   2   3   4
2   5   2   3   4   5   6   3   4   5   6   7   4
3   5   6   7   8   2   3   4   5   6   3   4   5
4   6   7   4   5   6   7   8   5   6   7   8   9

In [124]:
list(range(4,10,2))

[4, 6, 8]

In [125]:
list(range(4,10,.2))

TypeError: 'float' object cannot be interpreted as an integer

In [127]:
np.arange(4,10,0.2)

array([4. , 4.2, 4.4, 4.6, 4.8, 5. , 5.2, 5.4, 5.6, 5.8, 6. , 6.2, 6.4,
       6.6, 6.8, 7. , 7.2, 7.4, 7.6, 7.8, 8. , 8.2, 8.4, 8.6, 8.8, 9. ,
       9.2, 9.4, 9.6, 9.8])

In [132]:
a = np.array([[1,2], [3,4]])
b = np.array([[2,3], [4,5]])

In [133]:
a

array([[1, 2],
       [3, 4]])

In [134]:
b

array([[2, 3],
       [4, 5]])

In [135]:
a*b

array([[ 2,  6],
       [12, 20]])

In [136]:
# to do matrix multiplication
a@b

array([[10, 13],
       [22, 29]])

In [137]:
m=a@b

In [138]:
m

array([[10, 13],
       [22, 29]])

In [139]:
m/0

C:\Users\win11\AppData\Local\Temp\ipykernel_21968\3791875896.py:1: RuntimeWarning: divide by zero encountered in true_divide
  m/0


array([[inf, inf],
       [inf, inf]])