In [1]:
import numpy as np

In [2]:
# Numpy is Numerical Python derived from matlab

In [3]:
# at the end our system is going to understand array and matrix 

In [4]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [5]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [6]:
np.zeros((3,4,5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [7]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [8]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [9]:
np.ones(((4,5,3)))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [10]:
6+np.zeros((3,4))

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [11]:
np.empty((4,5))

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        1.33511562e-306, 1.11259940e-306],
       [1.60221208e-306, 2.11398144e-307, 1.69121231e-306,
        4.00544531e-307, 1.60220393e-306],
       [6.89806849e-307, 1.69118787e-306, 6.89811941e-307,
        1.86919921e-306, 6.23058028e-307],
       [3.56022682e-307, 7.56593017e-307, 1.33511018e-306,
        1.86916797e-306, 2.56765117e-312]])

In [12]:
np.linspace(2,6)

array([2.        , 2.08163265, 2.16326531, 2.24489796, 2.32653061,
       2.40816327, 2.48979592, 2.57142857, 2.65306122, 2.73469388,
       2.81632653, 2.89795918, 2.97959184, 3.06122449, 3.14285714,
       3.2244898 , 3.30612245, 3.3877551 , 3.46938776, 3.55102041,
       3.63265306, 3.71428571, 3.79591837, 3.87755102, 3.95918367,
       4.04081633, 4.12244898, 4.20408163, 4.28571429, 4.36734694,
       4.44897959, 4.53061224, 4.6122449 , 4.69387755, 4.7755102 ,
       4.85714286, 4.93877551, 5.02040816, 5.10204082, 5.18367347,
       5.26530612, 5.34693878, 5.42857143, 5.51020408, 5.59183673,
       5.67346939, 5.75510204, 5.83673469, 5.91836735, 6.        ])

In [13]:
np.linspace(2,8,15)

array([2.        , 2.42857143, 2.85714286, 3.28571429, 3.71428571,
       4.14285714, 4.57142857, 5.        , 5.42857143, 5.85714286,
       6.28571429, 6.71428571, 7.14285714, 7.57142857, 8.        ])

In [14]:
np.linspace(2,8,15).reshape(5,3)

array([[2.        , 2.42857143, 2.85714286],
       [3.28571429, 3.71428571, 4.14285714],
       [4.57142857, 5.        , 5.42857143],
       [5.85714286, 6.28571429, 6.71428571],
       [7.14285714, 7.57142857, 8.        ]])

In [15]:
np.linspace(1,10,13,endpoint=False)

array([1.        , 1.69230769, 2.38461538, 3.07692308, 3.76923077,
       4.46153846, 5.15384615, 5.84615385, 6.53846154, 7.23076923,
       7.92307692, 8.61538462, 9.30769231])

In [16]:
np.logspace(2,4,11,base=2)

array([ 4.        ,  4.59479342,  5.27803164,  6.06286627,  6.96440451,
        8.        ,  9.18958684, 10.55606329, 12.12573253, 13.92880901,
       16.        ])

In [17]:
a = np.arange(2,16)

In [18]:
a

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [19]:
a = np.arange(16).reshape(4,4)

In [20]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [21]:
a.max()

15

In [22]:
a = np.arange(4,40).reshape(2,6,3)

In [23]:
a

array([[[ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12],
        [13, 14, 15],
        [16, 17, 18],
        [19, 20, 21]],

       [[22, 23, 24],
        [25, 26, 27],
        [28, 29, 30],
        [31, 32, 33],
        [34, 35, 36],
        [37, 38, 39]]])

In [24]:
type(a)

numpy.ndarray

In [25]:
a.ndim

3

In [26]:
a.max()

39

In [27]:
a.max(axis=1)

array([[19, 20, 21],
       [37, 38, 39]])

In [28]:
a = np.arange(2,18).reshape(4,4)

In [29]:
a

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13],
       [14, 15, 16, 17]])

In [30]:
a**3

array([[   8,   27,   64,  125],
       [ 216,  343,  512,  729],
       [1000, 1331, 1728, 2197],
       [2744, 3375, 4096, 4913]], dtype=int32)

In [31]:
a = pow(a,2)

In [32]:
a

array([[  4,   9,  16,  25],
       [ 36,  49,  64,  81],
       [100, 121, 144, 169],
       [196, 225, 256, 289]], dtype=int32)

In [33]:
b= np.array([2,3,1,2])

In [34]:
b

array([2, 3, 1, 2])

In [35]:
a+b

array([[  6,  12,  17,  27],
       [ 38,  52,  65,  83],
       [102, 124, 145, 171],
       [198, 228, 257, 291]])

In [39]:
b= np.array([2,3,1,2]).reshape(1,-1)

In [40]:
b

array([[2, 3, 1, 2]])

In [44]:
b=b.T

In [45]:
b

array([[2],
       [3],
       [1],
       [2]])

In [46]:
a+b

array([[  6,  11,  18,  27],
       [ 39,  52,  67,  84],
       [101, 122, 145, 170],
       [198, 227, 258, 291]])

In [41]:
a+b

array([[  6,  12,  17,  27],
       [ 38,  52,  65,  83],
       [102, 124, 145, 171],
       [198, 228, 257, 291]])

In [47]:
x = np.array([1,2,3,4,5,6])

In [48]:
y=x    # known as solo copy

In [49]:
y

array([1, 2, 3, 4, 5, 6])

In [50]:
z = np.copy(x)  # known as deep copy

In [51]:
z

array([1, 2, 3, 4, 5, 6])

In [52]:
x[0] = 1000

In [53]:
y

array([1000,    2,    3,    4,    5,    6])

In [54]:
x

array([1000,    2,    3,    4,    5,    6])

In [55]:
z

array([1, 2, 3, 4, 5, 6])

In [66]:
id(x)

2452608027792

In [67]:
id(y)

2452608027792

In [68]:
id(z)

2452598915504

In [69]:
id(x[0])

2452630468976

In [70]:
id(y[0])

2452630468976

In [71]:
id(x[0]) == id(y[0])

True

In [72]:
id(x[0]) == id(y[1])

True